### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Matsv** [ViaVersion/ViaBackwards#6]
- [x] Multiplatform support (Sponge, Spigot, Bungee)
- [ ] Improve the rewriters (Packet templates, a lot packets are still the same between versions)
- [x] Make it possible to send metadata with the rewriteEntityId
- [ ] Add support for sound names
- [x] improve item names
- [x] Create JavaDocs
- [x] Improve the Entity tracker system to work good with multiple versions.
- [ ] Make it possible to choose your own replacement blocks
- [ ] Rewrite entity spawn eggs
- [ ] Handle spawner entities
- [x] Fix maps
- [ ] check potions 
- [ ] handle hologram offset
- [ ] 1.9 and 1.10 sound check

**Comment by Lmmb74** [comment]
*hypermegabump?

**Comment by Lmmb74** [comment]
Will you continue this project?

**Comment by Matsv** [comment]
Maybe in the future when I have more time. Sorry ):

**Comment by TheIntelloBox** [comment]
Make it possible to choose your own replacement blocks ? Please ! :D

**Comment by creeper123123321** [comment]
[ ] Rewrite Entity Properties packets

**Comment by KennyTV** [comment]
I'll prolly make a new/updated todo list in the near future 👀
